version: '3.8'

services:
  server:
    container_name: server
    build:
      dockerfile: devops/Dockerfile
      context: .
    entrypoint: [ "/server" ]
    environment:
      HOST: "0.0.0.0"
      PORT: 10001
      MAX_CONCURRENCY: 500
      ACCEPT_TIMEOUT: "1ms"
      POW_DIFFICULTY: 8
      POW_WRITE_TIMEOUT: "250ms"
      POW_READ_TIMEOUT: "500ms"
      PPROF_ENABLED: true
      PPROF_HOST: "0.0.0.0"
      PPROF_PORT: 6060
    ports:
      - "10001:10001"

  client:
    container_name: client
    build:
      dockerfile: devops/Dockerfile
      context: .
    entrypoint: [ "/client" ]
    environment:
      HOST: "server"
      PORT: 10001
      CLIENTS: 1000
      MAX_CONCURRENCY: 500
      DIAL_TIMEOUT: "1s"
      READ_TIMEOUT: "1s"
      WRITE_TIMEOUT: "1s"
